PKG_NAME="xorgproto"
PKG_VERSION="2018.4"
PKG_ARCH="any"
PKG_LICENSE="OSS"
PKG_SITE="http://www.x.org/"
PKG_URL="http://xorg.freedesktop.org/archive/individual/proto/$PKG_NAME-$PKG_VERSION.tar.bz2"
PKG_DEPENDS_HOST="util-macros:host"
PKG_DEPENDS_TARGET="toolchain util-macros"
PKG_SECTION="x11/proto"
PKG_SHORTDESC="X Window System Unified Protocol"

PKG_IS_ADDON="no"
PKG_AUTORECONF="no"
PKG_USE_MESON="no"
